# Generated by Django 4.1.1 on 2022-10-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_order_refund_granted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='type',
            field=models.CharField(choices=[('SELECT', 'Select Box'), ('RADIO', 'Radio Choices')], default='SELECT', max_length=10),
        ),
    ]
