# Generated by Django 4.1.1 on 2022-10-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='SA', max_length=100),
            preserve_default=False,
        ),
    ]
