# Generated by Django 4.1.1 on 2022-11-22 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='arabic_category',
        ),
    ]
