# Generated by Django 4.1.1 on 2022-11-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_sold',
            field=models.IntegerField(default=0, verbose_name='count sold'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='available_quantity',
            field=models.IntegerField(default=0, verbose_name='available quantity'),
        ),
    ]
