# Generated by Django 4.1.1 on 2022-10-03 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='الاسم يجب ان يتكون من احرف و ارقام', regex='^[\\w.@+\\- ]+$')]),
        ),
    ]
